theme: jekyll-theme-minimal
title: Recipie database
description: collection of recipies
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - cookies.md
  - smores-bars.md